// This file has been autogenerated from a class added in the UI designer.
using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Avgangsalarm.Core.Services;
using MonoTouch.MapKit;
using MonoTouch.CoreLocation;
using Avgangsalarm.Core;
using System.Text;

namespace Avgangsalarm.iOS
{
	public partial class MapViewController : UIViewController
	{
		IMonitorGeoFences _monitorGeoFences = DummyContainer.MonitorGeoFences; 
		ILocationRepository _repository = DummyContainer.LocationRepository;
		ILog _logger = LogManager.GetLogger(typeof(MapViewController));
		MKMapView _mapView; 

		public MapViewController (IntPtr handle) : base (handle)
		{

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Perform any additional setup after loading the view, typically from a nib.
			CreateMapView ();
		}

		void CreateMapView ()
		{
			_mapView = new MKMapView (UIScreen.MainScreen.Bounds);
			_mapView.ShowsUserLocation = true;
			View.InsertSubview (_mapView, 0);
		}
	}
}
