// This file has been autogenerated from a class added in the UI designer.
using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Avgangsalarm.Core.Services;
using MonoTouch.MapKit;
using MonoTouch.CoreLocation;
using Avgangsalarm.Core;
using System.Text;
using Avgangsalarm.iOS.Delegates;

namespace Avgangsalarm.iOS
{
	public partial class MapViewController : UIViewController
	{
		IMonitorGeoFences _monitorGeoFences = DummyContainer.MonitorGeoFences; 
		ILocationRepository _repository = DummyContainer.LocationRepository;
		ILog _logger = LogManager.GetLogger(typeof(MapViewController));
		MKMapView _mapView; 

		public MapViewController (IntPtr handle) : base (handle)
		{

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Perform any additional setup after loading the view, typically from a nib.
			CreateMapView ();
			ShowLocationsAsAnnotations ();
		}

		void CreateMapView ()
		{
			_mapView = new MKMapView (UIScreen.MainScreen.Bounds);
			_mapView.ShowsUserLocation = true;
			_mapView.Delegate = new MapViewDelegate ();
			View.InsertSubview (_mapView, 0);
		}

		void ShowLocationsAsAnnotations ()
		{
			var locations = _repository.FetchAll ();
					
			foreach (var l in locations) 
			{
				var annotation = new MKPointAnnotation 
				{
					Title = l.Name,
					Coordinate = new CLLocationCoordinate2D (l.Region.Latitude, l.Region.Longitude)
				};

				_mapView.AddAnnotation (annotation);

				var circleOverlay = MKCircle.Circle (annotation.Coordinate, l.Region.AlertZoneRadiusInMeters);
				_mapView.AddOverlay (circleOverlay);
			}
		}
	}
}
